import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { UnifiedReportResponse } from '../types/index';

// Format helper
export function formatCellValue(val: any, format?: string): string {
  if (val === null || val === undefined) return '-';
  if (format === 'currency') {
    const num = Number(val);
    return isNaN(num) ? String(val) : `₱${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }
  if (format === 'number') {
    const num = Number(val);
    return isNaN(num) ? String(val) : num.toLocaleString('en-US');
  }
  if (format === 'datetime') {
    try {
      const d = new Date(val);
      return isNaN(d.getTime()) ? String(val) : d.toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' });
    } catch {
      return String(val);
    }
  }
  if (format === 'date') {
    try {
      const d = new Date(val);
      return isNaN(d.getTime()) ? String(val) : d.toLocaleDateString('en-PH', { dateStyle: 'medium' });
    } catch {
      return String(val);
    }
  }
  return String(val);
}

// 1. CSV EXPORT
export function exportToCSV(report: UnifiedReportResponse): void {
  const headers = report.columns.map(c => c.label);
  const rows = report.rows.map(row => {
    return report.columns.map(col => {
      const val = row[col.id];
      const str = formatCellValue(val, col.format);
      // Escape CSV double quotes
      if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`;
      }
      return str;
    });
  });

  const metadataRows = [
    `"TAGPUAN ERP - ${report.report_name.toUpperCase()}"`,
    `"Period:","${report.period} (${report.start_date} to ${report.end_date})"`,
    `"Branch:","${report.branch_name}"`,
    `"Generated By:","${report.generated_by}"`,
    `"Generated At:","${new Date(report.generated_at).toLocaleString('en-PH')}"`,
    `"Total Rows:","${report.rows.length}"`,
    ''
  ];

  const csvContent = '\uFEFF' + metadataRows.join('\n') + '\n' + [
    headers.map(h => `"${h.replace(/"/g, '""')}"`).join(','),
    ...rows.map(r => r.join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Tagpuan_${report.report_type}_${report.start_date}_to_${report.end_date}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// 2. EXCEL (XLSX) EXPORT
export function exportToExcel(report: UnifiedReportResponse): void {
  const wb = XLSX.utils.book_new();

  // Prepare header info
  const meta = [
    ['TAGPUAN ERP - ' + report.report_name.toUpperCase()],
    ['Period', `${report.period} (${report.start_date} to ${report.end_date})`],
    ['Branch', report.branch_name],
    ['Generated By', report.generated_by],
    ['Generated At', new Date(report.generated_at).toLocaleString('en-PH')],
    ['Total Records', report.rows.length],
    []
  ];

  // Column header row
  const tableHeaders = report.columns.map(c => c.label);
  const dataRows = report.rows.map(row => {
    return report.columns.map(col => {
      const val = row[col.id];
      return formatCellValue(val, col.format);
    });
  });

  const wsData = [...meta, tableHeaders, ...dataRows];
  const ws = XLSX.utils.aoa_to_sheet(wsData);

  // Auto-column widths
  const colWidths = report.columns.map(col => ({
    wch: Math.max(col.label.length + 4, 15)
  }));
  ws['!cols'] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, report.report_name.slice(0, 30));
  XLSX.writeFile(wb, `Tagpuan_${report.report_type}_${report.start_date}_to_${report.end_date}.xlsx`);
}

// 3. PDF EXPORT
export function exportToPDF(report: UnifiedReportResponse): void {
  const doc = new jsPDF({
    orientation: report.columns.length > 7 ? 'landscape' : 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  // Header banner
  doc.setFontSize(16);
  doc.setTextColor(180, 20, 20); // Tagpuan primary red
  doc.text('TAGPUAN ENTERPRISE ERP', 40, 40);

  doc.setFontSize(12);
  doc.setTextColor(40, 40, 40);
  doc.text(report.report_name, 40, 58);

  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Branch: ${report.branch_name}  |  Period: ${report.period} (${report.start_date} to ${report.end_date})`, 40, 75);
  doc.text(`Generated By: ${report.generated_by}  |  Date: ${new Date(report.generated_at).toLocaleString('en-PH')}`, 40, 88);

  // Table
  const tableHeaders = [report.columns.map(c => c.label)];
  const tableRows = report.rows.map(row => {
    return report.columns.map(col => {
      const val = row[col.id];
      return formatCellValue(val, col.format);
    });
  });

  autoTable(doc, {
    head: tableHeaders,
    body: tableRows,
    startY: 105,
    margin: { left: 40, right: 40 },
    theme: 'grid',
    styles: {
      fontSize: 8,
      cellPadding: 4,
      overflow: 'linebreak'
    },
    headStyles: {
      fillColor: [30, 41, 59], // Slate 800
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // Slate 50
    },
    didDrawPage: (data) => {
      // Footer page numbering
      const str = `Page ${data.pageNumber} of ${(doc as any).internal.getNumberOfPages()}`;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(str, doc.internal.pageSize.width - 80, doc.internal.pageSize.height - 20);
      doc.text('Tagpuan ERP - Confidential Business Document', 40, doc.internal.pageSize.height - 20);
    }
  });

  doc.save(`Tagpuan_${report.report_type}_${report.start_date}_to_${report.end_date}.pdf`);
}
